name: 'Setup'
description: "Setups Node.js and yarn to run GitHub Actions' jobs."
runs:
  using: 'composite'
  steps:
    - name: 'Setup Node.js'
      uses: 'actions/setup-node@v3'
      with:
        node-version: '16.x'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
