name: 'Build, Publish and Release'

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]'

jobs:
  build-publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up yarn (Node 18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@hawapi'

      - name: Install dependencies
        run: yarn install

      ## Test, build and publish

      - name: Test, build and publish package
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ## Docs

      - name: Build docs
        run: yarn build:doc

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: kiprasmel/git-publish-generated-branch@v0
        with:
          ARGS: '--dir "docs" --branch "ph-pages"'
