name: 'Testing'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    if: github.event.pull_request.draft == false
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v3

      - name: Set up yarn (Node 18)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      ## Testing

      - name: Build project
        run: yarn test
